### ISSUE TITLE
Add: boggermytheme

### ISSUE THREAD

**Issue by Alerantt0** [cdnjs/packages#1162]
### Library name

bloggermytemplate

### Library license

https://github.com/Alerantt0/blogger/blob/main/LICENSE

### Library source

https://www.npmjs.com/package/bootstrap

### Files to include

styles

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [Policy, rules and guidelines](https://github.com/cdnjs/packages/blob/master/CONTRIBUTING.md#policy-rules-and-guidelines) for more information regarding this. 📖

Please open an issue or PR again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
