### ISSUE TITLE
es-chat Add: 0.1.0

### ISSUE THREAD

**Issue by 4nkit-5hukla** [cdnjs/packages#1413]
### Library name

es-chat

### Library license

NA

### Library source

https://www.npmjs.com/package/es-chat

### Files to include

./es.chat.min.js
./es.chat.js

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [Policy, rules and guidelines](https://github.com/cdnjs/packages/blob/master/CONTRIBUTING.md#policy-rules-and-guidelines) for more information regarding this. 📖

Please open an issue or PR again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
