### ISSUE TITLE
Add: clauswang v1.0.4

### ISSUE THREAD

**Issue by renrenguiwei** [cdnjs/packages#1465]
### Library name

clauswang

### Library license

https://github.com/renrenguiwei/clauswang/blob/master/LICENSE

### Library source

https://www.npmjs.com/package/clauswang

### Files to include

nothing

**Comment by renrenguiwei** [comment]
Is someone there?

**Comment by MattIPv4** [comment]
I maintain cdnjs, unpaid, in my spare time, when I have time :)

You are welcome to open a PR to add it yourself, which I will review when I can (probably at a weekend in the near future), or you can leave this issue open and I will look at adding it myself when I have time.

**Comment by renrenguiwei** [comment]
> I maintain cdnjs, unpaid, in my spare time, when I have time :)
> 
> You are welcome to open a PR to add it yourself, which I will review when I can (probably at a weekend in the near future), or you can leave this issue open and I will look at adding it myself when I have time.

Thank you. I'll wait for your response.

**Comment by renrenguiwei** [comment]
hello, I know you are very busy, if you have a moment sometime, please remember to take a look of this issue. Thank you.

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [Policy, rules and guidelines](https://github.com/cdnjs/packages/blob/master/CONTRIBUTING.md#policy-rules-and-guidelines) for more information regarding this. 📖

Please open an issue or PR again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
