### ISSUE TITLE
Add: DTS SelectJS

### ISSUE THREAD

**Issue by atdilshan** [cdnjs/packages#1567]
### Library name

DTS SelectJS

### Library license

https://github.com/devtech-squad/dts-selectjs/blob/master/LICENSE

### Library source

https://github.com/devtech-squad/dts-selectjs/tree/master/source

### Files to include

- [dts-selectjs.min.css](https://github.com/devtech-squad/dts-selectjs/blob/master/source/css/dts-selectjs.min.css)
- [dts-selectjs.min.js](https://github.com/devtech-squad/dts-selectjs/blob/master/source/js/dts-selectjs.min.js)

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [Policy, rules and guidelines](https://github.com/cdnjs/packages/blob/master/CONTRIBUTING.md#policy-rules-and-guidelines) for more information regarding this. 📖

Please open an issue or PR again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
