### ISSUE TITLE
Fetch latest version | Feature request 

### ISSUE THREAD

**Issue by nate-games** [cdnjs/packages#1628]
### Hello,
This is a recommendation that I would highly recommend if it doesn’t already exist 
Like jsDelivr, Unpkg, & Skypack. There should be a option that would fetch latest versions.

### For example

Instead of specifying a specific version you could simply add “/@fetch-latest/FILE” which would take you to the latest version and the file you specified.

I understand that this would take some time but this would be a great feature for **ALL** users.

I’m not sure if this feature already exists but please let me know.

**Comment by MattIPv4** [comment]
cdnjs does not support fetching the "latest" version directly, and has no intention of adding support for it. It removes the ability to implement best-practice security measures for third-party assets (SRI), and massively increases the chance if sites breaking due to libraries updating. This is discussed in our README: https://github.com/cdnjs/packages#latest-version-url-support
