### ISSUE TITLE
Update: `monaco-editor` from `0.49.0` to `0.50.0`

### ISSUE THREAD

**Issue by CetinSert** [cdnjs/packages#1837]
### Library name

monaco-editor

### Library JSON file

https://github.com/cdnjs/packages/blob/master/packages/m/monaco-editor.json

### Library source

https://www.npmjs.com/package/monaco-editor

### Files to include

Everything `0.49.0` does. See https://github.com/microsoft/monaco-editor/blob/main/CHANGELOG.md

---

✔️ https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.49.0/min/vs/loader.min.js
❌ https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.50.0/min/vs/loader.min.js

**Comment by CetinSert** [comment]
Still waiting…

**Comment by MattIPv4** [comment]
This is an open-source repo maintained by myself in my spare time for free. Feel free to open a PR yourself if you're waiting 😃

**Comment by CetinSert** [comment]
I will see what it takes!

I have simply assumed a large CDN would be fully automated and this version was just falling through the cracks.

**Comment by MattIPv4** [comment]
There is automation in place to pull in new versions but it gets stuck if the package structure changes. I haven't had time to look at what the issue is here. I'd look at the config JSON file and see if the config in there matches the expected structure in the source, or take a look in the cdnjs/logs repo to see if there was any obvious error logged for the version.

**Comment by CetinSert** [comment]
@MattIPv4 – fyi, lots of other work piled up on me, not active on this, but watching the issue daily (but quitely)!

**Comment by CetinSert** [comment]
✔️ https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.51.0/min/vs/loader.min.js
