### ISSUE TITLE
Add: keyfm

### ISSUE THREAD

**Issue by marinofranz** [cdnjs/packages#363]
**Library name:** keyfm

**Library license (include link):** https://github.com/marinofranz/keyfm-npm/blob/master/LICENSE

**Library source (NPM package or Git repo):** https://github.com/marinofranz/keyfm-npm - https://www.npmjs.com/package/keyfm

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm).

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
