### ISSUE TITLE
Unable to download twitter-bootstrap files using LibMan.

### ISSUE THREAD

**Issue by musyokaeric** [cdnjs/packages#396]
## Information
whatismybrowser.com/w/CM2HS5X

## Help request
Unable to download twitter-bootstrap files using LibMan.

### Problem
I'm tried to load bootstrap files onto my visual studio project using LibMan on VS2019, but the process eventually fails because the alert scss files fail to download.

### What I have tried
I first tried installing jquery files into my project and it works, but fails when I try to install twitter-bootstrap files

### Screenshots
jquery: success
![image](https://user-images.githubusercontent.com/62944492/90305080-4d99ba80-dec7-11ea-8212-43e9f675578e.png)

twitter-bootstrap: fail
![image](https://user-images.githubusercontent.com/62944492/90305095-74f08780-dec7-11ea-9b11-ee6fdba8c14f.png)

**Comment by MattIPv4** [comment]
@tc80 @xtuc This is a follow on from what was reported in https://github.com/cdnjs/cdnjs/issues/14003 -- it seems the bot is lacking logic to try re-adding those files or cleaning its local copy to match origin. This is resulting in it reporting files on the API that don't exist in the git origin.

The simple fix here is either to manually push the missing SCSS files up to GitHub or to clean the local git repo. But, really, we should look to fix this properly, so that the bot only ever reports files that are actually available.

**Comment by tc80** [comment]
There are about [32K files on disk](https://github.com/cdnjs/packages/files/5079168/files.txt) (not including nerd-fonts) that are not gitignored anymore, and have not been added to cdnjs/cdnjs.

@xtuc We should upload them to cdnjs/cdnjs ASAP to avoid any other issues.

They won't affect our current migration, since we are scraping files/metadata from disk. For example, we can see the `.scss` files:
```
curl http://metadata.speedcdnjs.com/packages/twitter-bootstrap/all | gzip -d
```

**Comment by tc80** [comment]
We will make the fix first thing on Monday 👍 .

**Comment by tc80** [comment]
`.scss` files are now on CDN 👍 

https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/scss/_alert.scss

**Comment by musyokaeric** [comment]
Work!! Thank you so much.
