### ISSUE TITLE
mdui-ext library request

### ISSUE THREAD

**Issue by LemonNekoGH** [cdnjs/packages#433]
**Library name:** mdui-ext

**Library license (include link):** MIT

**Library source (NPM package or Git repo):** https://github.com/LemonNekoGH/mdui-ext

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [Policy, rules and guidelines](https://github.com/cdnjs/packages/blob/master/CONTRIBUTING.md#policy-rules-and-guidelines) for more information regarding this. 📖

Please open an issue or PR again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
