### ISSUE TITLE
Add: Dizzle

### ISSUE THREAD

**Issue by varunsridharan** [cdnjs/packages#457]
**Library name:** Dizzle

**Library license (include link):** [MIT](https://github.com/varunsridharan/dizzle/blob/main/LICENSE)

**Library source (NPM package or Git repo):** 
* https://github.com/varunsridharan/dizzle
* https://npmjs.com/package/dizzle

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [Policy, rules and guidelines](https://github.com/cdnjs/packages/blob/master/CONTRIBUTING.md#policy-rules-and-guidelines) for more information regarding this. 📖

Please open an issue or PR again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄

**Comment by varunsridharan** [comment]
@MattIPv4 sorry about that. i was not sure and have no idea about it.!!
