### ISSUE TITLE
Add: userinterface.js

### ISSUE THREAD

**Issue by thoughtsunificator** [cdnjs/packages#467]
Library name: userinterface.js

Library license (include link): https://github.com/thoughtsunificator/userinterface.js/blob/master/LICENSE

Library source (NPM package or Git repo): https://github.com/thoughtsunificator/userinterface.js/

userinterface.js is a front-end library that helps organizing different parts of the UI into models.

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [Policy, rules and guidelines](https://github.com/cdnjs/packages/blob/master/CONTRIBUTING.md#policy-rules-and-guidelines) for more information regarding this. 📖

Please open an issue or PR again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄

**Comment by thoughtsunificator** [comment]
Hello,

Outright refusing because of a "number of stars"  in nonsense. Then how about the many libraries you host that are no longer maintained? OSS is not about popularity it's about sharing and learning.

**Comment by MattIPv4** [comment]
We have to use some metric to determine popularity of new libraries that we are adding so that we don't waste maintainer time adding every single library under the sun. The metric that we have used for many years now in 200 stars / 800 monthly NPM downloads.

These metrics give us an indication that a library has a decent number of users and as such is worth maintainer time to add to the CDN service.
