### ISSUE TITLE
prevent the minification (".min.js") files being created?

### ISSUE THREAD

**Issue by getify** [cdnjs/packages#555]
My npm packages come with pre-minified files in the `dist/` directory. However, I notice that this cdn automatically builds and adds new files into the directory, with `.min.js` extensions.

Some reasons this is not desired:

* it's unnecessary work
* my `dist/` files all have copyright notices included in them, and your minification is removing those comments -- these copyright notices also include the version of the file, and so with it being removed, I can't verify what version of the code someone might be using.
* it has the potential to cause confusion if someone is using a file from my package that I didn't create and didn't test/verify

I would like to configure my packages to prevent the auto-minification step you're performing. How can I do so?

**Comment by MattIPv4** [comment]
@tc80 could you look at adding this to the bot and package scheme?

**Comment by tc80** [comment]
this is interesting! At the moment, we are *supposedly* ignoring `.js` files that already come with minified forms (right [here](https://github.com/cdnjs/tools/blob/master/compress/js.go#L24-L33)), so this might just be a bug I created...

I'm assuming one of your packages having problems is [CAF](https://github.com/cdnjs/packages/blob/master/packages/c/caf.json)?

@xtuc can you grep the logs for `compressed file already exists`? I think the bug is that `os.Stat` won't return an error if the file exists, so the `!os.IsNotExist(err)` statement is never true. (I'll confirm this in a few minutes)

**Comment by tc80** [comment]
yep. It is just a [bug.](https://stackoverflow.com/questions/12518876/how-to-check-if-a-file-exists-in-go) Whoopsie.

**Comment by tc80** [comment]
@getify this should be fixed soon, please re-raise this issue if you notice auto-minification in your future releases 👍

**Comment by getify** [comment]
I may be misunderstanding the code, but it looks to me like you're checking to see if a file with `.min.js` extension exists... but that's not the way my `dist/` files are organized. I don't distribute any non-minified files, so my files (like `caf.js`) are just always going to have already been minified.

What I'm seeing is *not* that you're overwriting my files, but that you're unnecessarily *adding* `.min.js` files into my `dist/` folder that we're there, and (as far as I'm concerned) shouldn't be there.

**Comment by tc80** [comment]
Ah, gotcha. I just made an issue to add a JSON field to the package config soon for this #556 . I'll tag you when it's done 😄

**Comment by tc80** [comment]
might be a couple weeks because of holidays, but should get fixed 👍 . thanks

**Comment by KoalaBear84** [comment]
Programmers are bad at planning and estimates 😂

**Comment by tc80** [comment]
My apologies, totally lost track of this issue. Going to add the new field to the package config now. 👍

**Comment by tc80** [comment]
@getify sorry for the delay!

The fix is live. To prevent us from optimizing JS (and thus creating `.min.js` files), add to your JSON config:
```
"optimization": {
    "js": false
  }
```

I [updated my test package config](https://github.com/cdnjs/packages/pull/701/files#diff-b9f14653be4bb558ad3876376bc8eb195c71a55cdf929e2dedcfaaad13e52b92R26) and [it is currently ignoring `.min.js`](https://github.com/cdnjs/cdnjs/commit/dbd3be4e8a47c37fdd383a0d4342e49b9726e2cc) 😄

To prevent us from optimizing CSS, JPG/JPEG, and PNG files, you can also add properties similarly for `css`, `jpg`, and `png`. By default, all files will be optimized.

Thanks again for raising this issue and feel free to re-open this if you have any issues 😄 

cc @xtuc @MattIPv4
