### ISSUE TITLE
Update: chartjs-plugin-zoom is missing latest version (1.0.0-beta3/4/5)

### ISSUE THREAD

**Issue by KoalaBear84** [cdnjs/packages#722]
### Library name

chartjs-plugin-zoom

### Library JSON file

https://github.com/cdnjs/packages/blob/master/packages/c/chartjs-plugin-zoom.json

### Library source

https://www.npmjs.com/package/chartjs-plugin-zoom

### Files to include

- "**/*" (as it currently is?)

**Comment by MattIPv4** [comment]
:wave: We have ongoing maintenance with the auto-update functionality of cdnjs currently -- these versions were released since the maintenance started, and so our auto-update logic hasn't been running to detect them. Yo can follow along on our status page for when the maintenance will conclude: https://status.cdnjs.com/

**Comment by KoalaBear84** [comment]
I'm not pushing, but I'm curious because the maintenance has completed 5 days ago. But it looks like it has not catched up, will this be done automatically, or does it need another release?

**Comment by MattIPv4** [comment]
Hey! We've completed the core maintenance itself, but the bot is still marked as being under maintenance as we're slowly working to roll out the new auto-update system to packages. Our priority is to focus on newly added libraries and ones we know are outdated such as this one -- I imagine we'll be able to get this introduced to the new system next week :)

**Comment by KoalaBear84** [comment]
Great! 👍

**Comment by KoalaBear84** [comment]
Closing this one as this and chartjs-plugin-datalabels are updated to include all latest versions. Thanks!
