### ISSUE TITLE
Update: Bootstrap 5.0.1

### ISSUE THREAD

**Issue by drauch** [cdnjs/packages#739]
### Library name

twitter-bootstrap

### Library JSON file

https://github.com/cdnjs/packages/blob/master/packages/t/twitter-bootstrap.json

### Library source

https://www.npmjs.com/package/bootstrap/v/5.0.1

### Files to include

All the usual files

**Comment by MattIPv4** [comment]
👋 We have ongoing maintenance with the auto-update functionality of cdnjs currently -- this version was released since the maintenance started, and so our auto-update logic hasn't been running to detect it. You can follow along on our status page for when the maintenance will conclude: https://status.cdnjs.com/
