### ISSUE TITLE
[Request] [feikai2012] Add easyfaqs.js

### ISSUE THREAD

**Issue by feikai2012** [cdnjs/packages#765]
**Library name:** easyfaqs
**Git repository url:** [shopify/shopify][git-repository-url]
**License (List them all if it's multiple):** [MIT]
**Official homepage:** [https://shopify.com/][homepage]
**Wanna say something? Leave message here:** N/A

[license]:https://github.com/rsuite/rsuite/blob/master/LICENSE
[git-repository-url]: https://github.com/feikai2012/staticfile
[homepage]:http://rsuitejs.com/

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [Policy, rules and guidelines](https://github.com/cdnjs/packages/blob/master/CONTRIBUTING.md#policy-rules-and-guidelines) for more information regarding this. 📖

Please open an issue or PR again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
