### ISSUE TITLE
Add: Axios Multi Api

### ISSUE THREAD

**Issue by MattCCC** [cdnjs/packages#826]
### Library name

Axios Multi Api

### Library license

https://github.com/MattCCC/axios-multi-api/blob/master/LICENSE

### Library source

https://www.npmjs.com/package/axios-multi-api

**Comment by MattIPv4** [comment]
👋 It looks like the versions of the library available in your `dist` folder still rely on `require` calls to load other dependencies -- this won't work in a browser context, so I don't think we can add this library currently?

**Comment by MattCCC** [comment]
Hello @MattIPv4! Thank you for checking it out. I think I messed up the build process. I've separated it now, and browser esm builds are available under browser/ directory.

**Comment by MattIPv4** [comment]
I don't see a new release for this fix on NPM, nor a tag on GitHub.

For what its worth, I'd also strongly recommend providing UMD/CJS bundled versions of your library for the browser, so that folks that don't want to (or can't) use browser modules or don't want to have to separately load all your dependencies can still use your library.

**Comment by MattIPv4** [comment]
No progress, closing.
