### ISSUE TITLE
[Request] [Author] Add mtl.js

### ISSUE THREAD

**Issue by jiangzhenya110** [cdnjs/packages#833]
**Library name:** mtl-js-sdk
**Git repository url:** [mtl-js-sdk][https://github.com/jiangzhenya110/images.git]
**npm package name or url** (if there is one): [npmjs.com/package/mtl-js-sdk][https://www.npmjs.com/package/mtl-js-sdk]
**License (List them all if it's multiple):** [MIT][license]
**Official homepage:** [https://mobile.yyuap.com/mtl/home/index.html][homepage]
**Wanna say something? Leave message here:** N/A

[license]:https://github.com/jiangzhenya110/images/blob/master/LICENSE
[git-repository-url]: https://github.com/jiangzhenya110/images.git
[homepage]:https://mobile.yyuap.com/mtl/home/index.html
[npm]:https://www.npmjs.com/package/mtl-js-sdk

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [Policy, rules and guidelines](https://github.com/cdnjs/packages/blob/master/CONTRIBUTING.md#policy-rules-and-guidelines) for more information regarding this. 📖

Please open an issue or PR again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
